FROM golang:latest AS builder
WORKDIR /galah
COPY . .
RUN <<EOF
go mod download
go build -o galah ./cmd/galah
EOF

FROM registry.redhat.io/ubi10-micro@sha256:2a820c70ceee2588618f4b1b6116eaa38952b455e1f9fd3a91f7d8afb21c0873
WORKDIR /
COPY --from=builder /galah/galah /
EXPOSE 8080
USER 1001
ENTRYPOINT ["./galah"]
